---
- hosts: all
  gather_facts: true
  become: true
  become_method: sudo
  become_user: root
  vars:
    bro_ver: "3.2.2"
    bro_dir: "/opt/zeek"
    pfring_dir: "/opt/pfring"
  tasks:
    - include: ./task/bro_tasks.yml
