---
- hosts: all
  gather_facts: true
  become: true
  become_method: sudo
  become_user: root
  vars:
    pfring_ver: "7.8.0"
    pfring_dir: "/opt/pfring"
    min_num_slots: 8192
  tasks:
    - include: ./task/pfring_tasks.yml
