---
- hosts: all
  gather_facts: true
  become: true
  become_method: sudo
  become_user: root
  vars:
    suricata_ver: "6.0.0"
    pfring_dir: "/opt/pfring"
    suricata_dir: "/opt/suricata"
  tasks:
    - include: ./task/suricata_tasks.yml
