---
- hosts: all
  gather_facts: true
  become: true
  become_method: sudo
  become_user: root
  vars:
    zeek_ver: "4.0.3"
    zeek_dir: "/opt/zeek"
    pfring_dir: "/opt/pfring"
  tasks:
    - include: ./task/zeek_tasks.yml
