- name: install dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- name: install dependencies for build
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - git
    - gcc
    - make
    - libc-dev
  when: beat_compile_src is defined and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- apt_key:
    id: D88E42B4
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present
  when: beat_compile_src is not defined and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- apt_repository:
    repo: deb https://artifacts.elastic.co/packages/6.x/apt stable main
    state: present
  when: beat_compile_src is not defined and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- name: install metricbeat
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - metricbeat
  when: beat_compile_src is not defined and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- name: Create config directory
  file: path=/etc/metricbeat/ state=directory
  when: beat_compile_src is defined and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- name: Create data directory
  file: path=/var/lib/metricbeat/ state=directory
  when: beat_compile_src is defined and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- name: Create log directory
  file: path=/var/log/metricbeat/ state=directory
  when: beat_compile_src is defined and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

## Download golang
- name: Download golang
  get_url:
    url: https://dl.google.com/go/go{{golang_version}}.linux-amd64.tar.gz
    dest: /tmp/go{{golang_version}}.linux.tar.gz
  when: golang_arch is not defined and beat_compile_src is defined and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- name: Download golang
  get_url:
    url: https://dl.google.com/go/go{{golang_version}}.linux-{{golang_arch}}.tar.gz
    dest: /tmp/go{{golang_version}}.linux.tar.gz
  when: golang_arch is defined and beat_compile_src is defined and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- name: Extract golang archive
  unarchive:
    src: /tmp/go{{golang_version}}.linux.tar.gz
    dest: /usr/local
    remote_src: yes
  when: beat_compile_src is defined and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- name: Create go home directory
  file: path=/opt/go state=directory
  when: beat_compile_src is defined and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- name: build metricbeat binary
  shell: |
    cd /opt/go
    go get github.com/elastic/beats
    cd /opt/go/src/github.com/elastic/beats/
    git checkout v6.5.0
    cd /opt/go/src/github.com/elastic/beats/metricbeat/
    make
    mv metricbeat /usr/bin/.
  args:
    executable: /bin/bash
  environment:
    GOPATH: "/opt/go"
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin"
  when: beat_compile_src is defined and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- template:
   src: './template/metric/metricbeat.service'
   dest: '/etc/systemd/system/metricbeat.service'
   mode: 0755
  when: beat_compile_src is defined and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- template:
   src: './template/metric/metricbeat.yml.j2'
   dest: '/etc/metricbeat/metricbeat.yml'

- name: Enable service metricbeat
  service:
    name: metricbeat
    enabled: yes
  when: beat_compile_src is not defined and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- name: Enable service metricbeat
  shell: 'systemctl enable metricbeat'
  when: beat_compile_src is defined and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
