---
- hosts: all
  gather_facts: true
  become: true
  become_method: sudo
  become_user: root
  vars:
    setup_ap: false # set to true to setup an AP
    setup_tor: false # set to true to setup an Tor
  tasks:
    - include_vars: "./var/gate_vars.yml"
    - include: ./task/gateway_tasks.yml
    - include: ./task/hostapd_tasks.yml
      when: setup_ap == true
    - include: ./task/tor_tasks.yml
      when: setup_tor == true
