---
- hosts: all
  gather_facts: true
  become: true
  become_method: sudo
  become_user: root
  vars:
    ap_ssid: 'PleaseChangeMe'
    ap_nic: 'wlan0'
  tasks:
    - include: ./task/hostapd_tasks.yml
