---
- hosts: all
  gather_facts: true
  become: true
  become_method: sudo
  become_user: root
  vars:
    mydom: 'pleasechange.me'
    unbound_root_dir: '/etc/unbound'
  tasks:
    - include_vars: "./var/gate_vars.yml"
    - include: ./task/gateway_tasks.yml
