- name: Install elasticsearch ingest geoip plugin
  shell: '/usr/share/elasticsearch/bin/elasticsearch-plugin install -b ingest-geoip'

- name: Start service elasticsearch
  service:
    name: elasticsearch
    state: restarted
