- apt_key:
    id: D88E42B4
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- name: install dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- name: install kibana
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - kibana
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- lineinfile:
    dest: /etc/kibana/kibana.yml
    line: 'server.host: "{{kibana_host}}"'
  when: kibana_host is defined and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- lineinfile:
    dest: /etc/kibana/kibana.yml
    line: 'elasticsearch.requestTimeout: {{kibana_requesttimeout}}'
  when: kibana_requesttimeout is defined and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- name: Enable service kibana
  service:
    name: kibana
    enabled: yes
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
