- name: install samba nginx
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - samba
    - nginx
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install bsd packages
  openbsd_pkg:
    name: "{{ packages }}"
  vars:
    packages:
    - samba
  when: ansible_distribution == 'OpenBSD'

- name: Create /nfs/pub
  file: path=/nfs/pub state=directory mode=0777
  when: ansible_distribution == 'OpenBSD'

- lineinfile:
   dest: '/etc/exports'
   create: true
   line: '/nfs/pub -alldirs -ro'
  when: ansible_distribution == 'OpenBSD'

- name: enable nfs services
  shell: 'rcctl enable portmap mountd nfsd'
  when: ansible_distribution == 'OpenBSD'

- name: Create /var/www/htdocs/pub/
  file: path=/var/www/htdocs/pub state=directory mode=0755
  when: ansible_distribution == 'OpenBSD'

- template:
   src: './template/index.html.j2'
   dest: '/var/www/htdocs/index.html'
  when: ansible_distribution == 'OpenBSD'

- template:
   src: './template/httpd.conf.j2'
   dest: '/etc/httpd.conf'
  when: ansible_distribution == 'OpenBSD'

- name: enable httpd service
  command: rcctl enable httpd
  when: ansible_distribution == 'OpenBSD'

- name: Create /share/pub
  file: path=/share/pub state=directory mode=0777

- name: Samba share conf
  blockinfile:
    dest: /etc/samba/smb.conf
    block: |
      [pub]
         comment = Public file space
         path = /share/pub
         read only = no
         public = yes
         force user = nobody
         max connections = 10
         create mask = 0775

- name: enable samba services
  shell: 'rcctl enable smbd nmbd'
  when: ansible_distribution == 'OpenBSD'

- name: Enable service smbd
  service:
    name: smbd
    enabled: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Enable service nmbd
  service:
    name: nmbd
    enabled: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Create /var/www/html/pub
  file: path=/var/www/html/pub state=directory mode=0755
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- template:
   src: './template/index.html.j2'
   dest: '/var/www/html/index.html'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- template:
   src: './template/nginx.conf.j2'
   dest: '/etc/nginx/sites-enabled/default'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Enable service nginx
  service:
    name: nginx
    enabled: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
