---
- hosts: all
  gather_facts: true
  remote_user: pi
  become: true
  become_method: sudo
  become_user: root
  vars:
    elastic_ver: '6.6.0'
    elastic_no_repo: true
    disable_xpack_ml: true
    is_single_node: true
    data_dir: '/data/elasticsearch'
  tasks:
    - include_vars: "./var/elastik_vars.yml"
    - include: ./task/elastic_tasks.yml
    - include: ./task/elastic_plugins_tasks.yml
    - include: ./task/curator_tasks.yml
    - include: ./task/nginx_tasks.yml
