---
- hosts: all
  gather_facts: true
  remote_user: pi
  become: true
  become_method: sudo
  become_user: root
  vars:
    elastic_ver: '6.5.0'
    elastic_no_repo: true
    disable_xpack_ml: true
    is_single_node: true
  tasks:
    - include_vars: "./var/elastic.yml"
    - include: ./task/elastic_tasks.yml
    - include: ./task/elastic_template_tasks.yml
    - include: ./task/elastic_plugins_tasks.yml
    - include: ./task/nginx_tasks.yml
