---
- hosts: all
  gather_facts: true
  remote_user: toor
  become: true
  become_method: sudo
  become_user: root
  vars:
    data_dir: '/data/elasticsearch'
  tasks:
    - include_vars: "./var/elastik_vars.yml"
    - include: ./task/elastic_tasks.yml
    - include: ./task/elastic_plugins_tasks.yml
    - include: ./task/curator_tasks.yml
    #- include: ./task/kibana_tasks.yml
    - include: ./task/nginx_tasks.yml
