---
- hosts: all
  gather_facts: true
  remote_user: toor
  become: true
  become_method: sudo
  become_user: root
  vars:
    net_host_site: true
    data_dir: '/home/elasticsearch'
    curator_dir: '/home/curator'
  tasks:
    - include_vars: "./var/elastik_vars.yml"
    - include: ./task/elastic_tasks.yml
    - include: ./task/kibana_tasks.yml
    - include: ./task/curator_tasks.yml
